### ISSUE TITLE
Support Angular 9

### ISSUE THREAD

**Issue by JaxonWright** [rameezv/LastFmScrobblesWidget#5]
Angular 9 released today. I was all ready to update to it, but I get the following error upon building:

![image](https://user-images.githubusercontent.com/14099593/73994941-3335c180-4925-11ea-98d7-2a915f902de9.png)

**Comment by rameezv** [comment]
Updated to support major versions of angular between 9 and 15. Should work with any version now! Sorry ir took so long

**Comment by JaxonWright** [comment]
Thank you!
